// Generated by tools/cut_music.py — beat-aligned music beds (frame 0 = downbeat).
// beatFrame(n) = Math.round(n * beat_frames). Cue frames are where the music event lands.
export const MUSIC = {
  "buscando": {
    "file": "music/buscando.wav",
    "song": "Rise and Grind",
    "bpm": 132.1,
    "beat_frames": 13.626,
    "bar_frames": 54.5042,
    "duration_s": 30.886,
    "duration_frames": 926,
    "cues": {
      "tension_bar": {
        "s": 9.084,
        "frame": 273
      },
      "drop": {
        "s": 10.901,
        "frame": 327
      },
      "energy_down_endcard": {
        "s": 25.436,
        "frame": 763
      }
    }
  },
  "buscando_calma": {
    "file": "music/buscando_calma.wav",
    "song": "Rise and Grind",
    "bpm": 132.1,
    "beat_frames": 13.626,
    "bar_frames": 54.5042,
    "duration_s": 39.97,
    "duration_frames": 1199,
    "cues": {
      "tension_bar": {
        "s": 16.351,
        "frame": 491
      },
      "drop": {
        "s": 18.168,
        "frame": 545
      },
      "energy_down_endcard": {
        "s": 32.703,
        "frame": 981
      }
    }
  },
  "manifiesto": {
    "file": "music/manifiesto.wav",
    "song": "Night Drift",
    "bpm": 131.8,
    "beat_frames": 13.6571,
    "bar_frames": 54.6282,
    "duration_s": 21.851,
    "duration_frames": 655,
    "cues": {
      "dip_start": {
        "s": 7.283,
        "frame": 218
      },
      "slam_back": {
        "s": 14.567,
        "frame": 437
      }
    }
  },
  "despegue": {
    "file": "music/despegue.wav",
    "song": "The Ticking Overture (v2)",
    "bpm": 100.0,
    "beat_frames": 18.0,
    "bar_frames": 72.0,
    "duration_s": 28.8,
    "duration_frames": 864,
    "cues": {
      "loud_bar": {
        "s": 9.6,
        "frame": 288
      },
      "fade_starts": {
        "s": 15.524,
        "frame": 466
      },
      "silence": {
        "s": 18.724,
        "frame": 562
      },
      "impact": {
        "s": 20.179,
        "frame": 605
      },
      "calm_endcard": {
        "s": 26.4,
        "frame": 792
      }
    }
  },
  "pov": {
    "file": "music/pov.wav",
    "song": "Cozy Afternoon",
    "bpm": 85.9,
    "beat_frames": 20.9546,
    "bar_frames": 83.8184,
    "duration_s": 30.733,
    "duration_frames": 921,
    "cues": {
      "breakdown": {
        "s": 11.176,
        "frame": 335
      },
      "groove_back": {
        "s": 19.558,
        "frame": 587
      }
    }
  },
  "trabajo": {
    "file": "music/trabajo.wav",
    "song": "Latin Funk Groove",
    "bpm": 121.8,
    "beat_frames": 14.7783,
    "bar_frames": 59.1133,
    "duration_s": 25.616,
    "duration_frames": 768,
    "cues": {
      "dip": {
        "s": 3.941,
        "frame": 118
      },
      "drop": {
        "s": 7.882,
        "frame": 236
      }
    }
  },
  "rebrand": {
    "file": "music/rebrand.wav",
    "song": "Cold to Warm",
    "bpm": 92.2,
    "beat_frames": 19.5228,
    "bar_frames": 78.0911,
    "duration_s": 31.304,
    "duration_frames": 939,
    "cues": {
      "splice": {
        "s": 10.48,
        "frame": 314
      },
      "bloom": {
        "s": 15.686,
        "frame": 471
      }
    }
  },
  "notis": {
    "file": "music/notis.wav",
    "song": "Playful Plucks",
    "bpm": 120.0,
    "beat_frames": 15.0,
    "bar_frames": 60.0,
    "duration_s": 12.0,
    "duration_frames": 360,
    "cues": {
      "loop_point": {
        "s": 12.0,
        "frame": 360
      }
    }
  }
} as const;
export const beatFrame = (bpm: number, n: number, fps = 30) => Math.round((n * 60 * fps) / bpm);
