import React from "react";
import { Audio } from "@remotion/media";
import { Sequence, staticFile, useVideoConfig } from "remotion";

/** Original SFX kit generated by tools/make_sfx.py (no third-party license). */
export type SfxName =
  | "whoosh_fast"
  | "whoosh_med"
  | "whoosh_long"
  | "whoosh_down"
  | "swipe"
  | "impact_big"
  | "impact_short"
  | "boom_sub"
  | "snap"
  | "riser_2s"
  | "riser_4s"
  | "ui_click"
  | "ui_tap"
  | "pop"
  | "notif_ding"
  | "notif_msg"
  | "success_chime"
  | "phone_ring"
  | "typing"
  | "glitch_1"
  | "glitch_2"
  | "tick"
  | "shutter"
  | "tape_stop";

/**
 * Place a sound effect at an absolute frame. `at` is the frame where the sound starts
 * (for risers/whooshes that should *land* on a cut, start them earlier).
 */
export const Sfx: React.FC<{ name: SfxName; at: number; volume?: number }> = ({
  name,
  at,
  volume = 0.8,
}) => {
  const { fps } = useVideoConfig();
  return (
    <Sequence from={Math.max(0, Math.round(at))} premountFor={fps} name={`sfx:${name}`}>
      <Audio src={staticFile(`sfx/${name}.wav`)} volume={volume} />
    </Sequence>
  );
};

/** Background music bed with fade in/out (frames). */
export const Music: React.FC<{
  src: string;
  volume?: number;
  fadeIn?: number;
  fadeOut?: number;
  trimBefore?: number;
  durationInFrames: number;
}> = ({ src, volume = 0.9, fadeIn = 6, fadeOut = 24, trimBefore = 0, durationInFrames }) => {
  return (
    <Audio
      src={staticFile(src)}
      trimBefore={trimBefore}
      volume={(f) => {
        const a = Math.min(1, f / Math.max(1, fadeIn));
        const b = Math.min(1, (durationInFrames - f) / Math.max(1, fadeOut));
        return Math.max(0, Math.min(a, b)) * volume;
      }}
    />
  );
};
